version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on: 
      - mysql
    restart: on-failure
#    environment:
#      - "ConnectionStrings:DatabaseConnection=server=mysql;database=Cardapio;user=root;password=1232"
    networks:
      - ingress

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql # usado externo, fica no host mas o compose não pode excluir
    command: ['--max_allowed_packet=32505856', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_DATABASE=Cardapio
      - MYSQL_ROOT_PASSWORD=1232
    networks:
      - ingress
    
  
networks:
  ingress:
    driver: bridge
    
volumes:
  dbdata:
    external: true